import { z } from "zod"

export const PostAdminCreateNewebpayConfig = z.object({
    Version:z.string(),
    LangType: z.string().optional(),
    TradeLimit: z.coerce.number().optional(),
    ExpireDate:z.string().optional(),
    ExpireTime:z.string().optional(),
    ReturnURL:z.string(),
    NotifyURL:z.string(),
    CustomerURL:z.string().optional(),
    ClientBackURL:z.string().optional(),
    EmailModify:z.coerce.number().optional(),
    OrderComment:z.string().optional(),
    CREDIT:z.coerce.number().optional(),
    APPLEPAY:z.coerce.number().optional(),
    ANDROIDPAY:z.coerce.number().optional(),
    SAMGSUNGPAY:z.coerce.number().optional(),
    LINEPAY:z.coerce.number().optional(),
    ImageUrl:z.string().optional(),
    InstFlag:z.coerce.number().optional(),
    CreditRed:z.coerce.number().optional(),
    UNIONPAY:z.coerce.number().optional(),
    CREDITAE:z.coerce.number().optional(),
    WEBATM:z.coerce.number().optional(),
    VACC:z.coerce.number().optional(),
    BankType:z.coerce.number().optional(),
    SourceType:z.coerce.number().optional(),
    SourceBankId:z.coerce.number().optional(),
    SourceAccountNo:z.coerce.number().optional(),
    CVS:z.coerce.number().optional(),
    BARCODE:z.coerce.number().optional(),
    ESUNWALLET:z.coerce.number().optional(),
    TAIWANPAY:z.coerce.number().optional(),
    BITOPAY:z.coerce.number().optional(),
    CVSCOM:z.coerce.number().optional(),
    TWQR:z.coerce.number().optional(),
    TWQR_LifeTime:z.coerce.number().optional(),
    EZPWECHAT:z.coerce.number().optional(),
    EZPALIPAY:z.coerce.number().optional(),
    LGSTYPE:z.coerce.string().optional(),
    WalletDisplayMode:z.coerce.number().optional()
})